package de.fabmax.kool.util

import de.fabmax.kool.math.*


context(view: StructBufferView<T>)
fun <T: Struct> Float1Member<T>.get(): Float = view.get(this)
context(view: StructBufferView<T>)
fun <T: Struct> Float2Member<T>.get(result: MutableVec2f) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float3Member<T>.get(result: MutableVec3f) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float4Member<T>.get(result: MutableVec4f) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float4Member<T>.get(result: MutableQuatF) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float4Member<T>.get(result: MutableColor) = view.get(this, result)

context(view: StructBufferView<T>)
fun <T: Struct> Int1Member<T>.get(): Int = view.get(this)
context(view: StructBufferView<T>)
fun <T: Struct> Int2Member<T>.get(result: MutableVec2i) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Int3Member<T>.get(result: MutableVec3i) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Int4Member<T>.get(result: MutableVec4i) = view.get(this, result)

context(view: StructBufferView<T>)
fun <T: Struct> Uint1Member<T>.get(): UInt = view.get(this)
context(view: StructBufferView<T>)
fun <T: Struct> Uint2Member<T>.get(result: MutableVec2i) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Uint3Member<T>.get(result: MutableVec3i) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Uint4Member<T>.get(result: MutableVec4i) = view.get(this, result)

context(view: StructBufferView<T>)
fun <T: Struct> Bool1Member<T>.get(): Boolean = view.get(this)
context(view: StructBufferView<T>)
fun <T: Struct> Bool2Member<T>.get(result: MutableVec2i) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Bool3Member<T>.get(result: MutableVec3i) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Bool4Member<T>.get(result: MutableVec4i) = view.get(this, result)

context(view: StructBufferView<T>)
fun <T: Struct> Mat2Member<T>.get(result: MutableMat2f) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Mat3Member<T>.get(result: MutableMat3f) = view.get(this, result)
context(view: StructBufferView<T>)
fun <T: Struct> Mat4Member<T>.get(result: MutableMat4f) = view.get(this, result)

context(view: StructBufferView<T>)
fun <T: Struct> Float1ArrayMember<T>.get(index: Int): Float = view.get(this, index)
context(view: StructBufferView<T>)
fun <T: Struct> Float2ArrayMember<T>.get(index: Int, result: MutableVec2f) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float3ArrayMember<T>.get(index: Int, result: MutableVec3f) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float4ArrayMember<T>.get(index: Int, result: MutableVec4f) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float4ArrayMember<T>.get(index: Int, result: MutableQuatF) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Float4ArrayMember<T>.get(index: Int, result: MutableColor) = view.get(this, index, result)

context(view: StructBufferView<T>)
fun <T: Struct> Int1ArrayMember<T>.get(index: Int): Int = view.get(this, index)
context(view: StructBufferView<T>)
fun <T: Struct> Int2ArrayMember<T>.get(index: Int, result: MutableVec2i) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Int3ArrayMember<T>.get(index: Int, result: MutableVec3i) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Int4ArrayMember<T>.get(index: Int, result: MutableVec4i) = view.get(this, index, result)

context(view: StructBufferView<T>)
fun <T: Struct> Uint1ArrayMember<T>.get(index: Int): UInt = view.get(this, index)
context(view: StructBufferView<T>)
fun <T: Struct> Uint2ArrayMember<T>.get(index: Int, result: MutableVec2i) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Uint3ArrayMember<T>.get(index: Int, result: MutableVec3i) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Uint4ArrayMember<T>.get(index: Int, result: MutableVec4i) = view.get(this, index, result)

context(view: StructBufferView<T>)
fun <T: Struct> Bool1ArrayMember<T>.get(index: Int): Boolean = view.get(this, index)
context(view: StructBufferView<T>)
fun <T: Struct> Bool2ArrayMember<T>.get(index: Int, result: MutableVec2i) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Bool3ArrayMember<T>.get(index: Int, result: MutableVec3i) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Bool4ArrayMember<T>.get(index: Int, result: MutableVec4i) = view.get(this, index, result)

context(view: StructBufferView<T>)
fun <T: Struct> Mat2ArrayMember<T>.get(index: Int, result: MutableMat2f) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Mat3ArrayMember<T>.get(index: Int, result: MutableMat3f) = view.get(this, index, result)
context(view: StructBufferView<T>)
fun <T: Struct> Mat4ArrayMember<T>.get(index: Int, result: MutableMat4f) = view.get(this, index, result)

context(view: StructBufferView<T>)
fun <T: Struct, N: Struct> NestedStructMember<T, N>.get(block: StructBufferView<N>.(N) -> Unit) = view.get(this, block)
context(view: StructBufferView<T>)
fun <T: Struct, N: Struct> NestedStructArrayMember<T, N>.get(index: Int, block: StructBufferView<N>.(N) -> Unit) = view.get(this, index, block)


context(view: MutableStructBufferView<T>)
fun <T: Struct> Float1Member<T>.set(x: Float) = view.set(this, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float2Member<T>.set(x: Float, y: Float) = view.set(this, x, y)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float2Member<T>.set(v: Vec2f) = set(v.x, v.y)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float3Member<T>.set(x: Float, y: Float, z: Float) = view.set(this, x, y, z)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float3Member<T>.set(v: Vec3f) = set(v.x, v.y, v.z)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float4Member<T>.set(x: Float, y: Float, z: Float, w: Float) = view.set(this, x, y, z, w)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float4Member<T>.set(v: Vec4f) = set(v.x, v.y, v.z, v.w)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float4Member<T>.set(q: QuatF) = set(q.x, q.y, q.z, q.w)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float4Member<T>.set(c: Color) = set(c.r, c.g, c.b, c.a)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Int1Member<T>.set(x: Int) = view.set(this, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int2Member<T>.set(x: Int, y: Int) = view.set(this, x, y)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int2Member<T>.set(v: Vec2i) = set(v.x, v.y)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int3Member<T>.set(x: Int, y: Int, z: Int) = view.set(this, x, y, z)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int3Member<T>.set(v: Vec3i) = set(v.x, v.y, v.z)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int4Member<T>.set(x: Int, y: Int, z: Int, w: Int) = view.set(this, x, y, z, w)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int4Member<T>.set(v: Vec4i) = set(v.x, v.y, v.z, v.w)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint1Member<T>.set(x: UInt) = view.set(this, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint2Member<T>.set(x: UInt, y: UInt) = view.set(this, x, y)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint2Member<T>.set(v: Vec2i) = view.set(this, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint3Member<T>.set(x: UInt, y: UInt, z: UInt) = view.set(this, x, y, z)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint3Member<T>.set(v: Vec3i) = view.set(this, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint4Member<T>.set(x: UInt, y: UInt, z: UInt, w: UInt) = view.set(this, x, y, z, w)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint4Member<T>.set(v: Vec4i) = view.set(this, v)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool1Member<T>.set(x: Boolean) = view.set(this, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool2Member<T>.set(v: Vec2i) = view.set(this, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool3Member<T>.set(v: Vec3i) = view.set(this, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool4Member<T>.set(v: Vec4i) = view.set(this, v)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Mat2Member<T>.set(v: Mat2f) = view.set(this, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Mat3Member<T>.set(v: Mat3f) = view.set(this, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Mat4Member<T>.set(v: Mat4f) = view.set(this, v)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Float1ArrayMember<T>.set(index: Int, x: Float) = view.set(this, index, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float2ArrayMember<T>.set(index: Int, v: Vec2f) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float3ArrayMember<T>.set(index: Int, v: Vec3f) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float4ArrayMember<T>.set(index: Int, v: Vec4f) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float4ArrayMember<T>.set(index: Int, q: QuatF) = view.set(this, index, q)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Float4ArrayMember<T>.set(index: Int, c: Color) = view.set(this, index, c)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Int1ArrayMember<T>.set(index: Int, x: Int) = view.set(this, index, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int2ArrayMember<T>.set(index: Int, v: Vec2i) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int3ArrayMember<T>.set(index: Int, v: Vec3i) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Int4ArrayMember<T>.set(index: Int, v: Vec4i) = view.set(this, index, v)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint1ArrayMember<T>.set(index: Int, x: UInt) = view.set(this, index, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint2ArrayMember<T>.set(index: Int, v: Vec2i) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint3ArrayMember<T>.set(index: Int, v: Vec3i) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Uint4ArrayMember<T>.set(index: Int, v: Vec4i) = view.set(this, index, v)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool1ArrayMember<T>.set(index: Int, x: Boolean) = view.set(this, index, x)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool2ArrayMember<T>.set(index: Int, v: Vec2i) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool3ArrayMember<T>.set(index: Int, v: Vec3i) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Bool4ArrayMember<T>.set(index: Int, v: Vec4i) = view.set(this, index, v)

context(view: MutableStructBufferView<T>)
fun <T: Struct> Mat2ArrayMember<T>.set(index: Int, v: Mat2f) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Mat3ArrayMember<T>.set(index: Int, v: Mat3f) = view.set(this, index, v)
context(view: MutableStructBufferView<T>)
fun <T: Struct> Mat4ArrayMember<T>.set(index: Int, v: Mat4f) = view.set(this, index, v)
