package de.fabmax.kool.pipeline.compat

import de.fabmax.kool.math.*
import de.fabmax.kool.modules.ksl.blocks.ColorBlockConfig
import de.fabmax.kool.modules.ksl.blocks.NormalMapConfig
import de.fabmax.kool.modules.ksl.blocks.PropertyBlockConfig
import de.fabmax.kool.pipeline.*
import de.fabmax.kool.util.Color
import de.fabmax.kool.util.Struct


@Deprecated("Use bindUniformFloat1 instead", replaceWith = ReplaceWith("bindUniformFloat1"))
fun ShaderBase<*>.uniform1f(uniformName: String, defaultVal: Float = 0f) = bindUniformFloat1(uniformName, defaultVal)
@Deprecated("Use bindUniformFloat2 instead", replaceWith = ReplaceWith("bindUniformFloat2"))
fun ShaderBase<*>.uniform2f(uniformName: String, defaultVal: Vec2f = Vec2f.ZERO) = bindUniformFloat2(uniformName, defaultVal)
@Deprecated("Use bindUniformFloat3 instead", replaceWith = ReplaceWith("bindUniformFloat3"))
fun ShaderBase<*>.uniform3f(uniformName: String, defaultVal: Vec3f = Vec3f.ZERO) = bindUniformFloat3(uniformName, defaultVal)
@Deprecated("Use bindUniformFloat4 instead", replaceWith = ReplaceWith("bindUniformFloat4"))
fun ShaderBase<*>.uniform4f(uniformName: String, defaultVal: Vec4f = Vec4f.ZERO) = bindUniformFloat4(uniformName, defaultVal)
@Deprecated("Use bindUniformColor instead", replaceWith = ReplaceWith("bindUniformColor"))
fun ShaderBase<*>.uniformColor(uniformName: String, defaultVal: Color = Color.BLACK) = bindUniformColor(uniformName, defaultVal)
@Deprecated("Use bindUniformQuat instead", replaceWith = ReplaceWith("bindUniformQuat"))
fun ShaderBase<*>.uniformQuat(uniformName: String, defaultVal: QuatF = QuatF.IDENTITY) = bindUniformQuat(uniformName, defaultVal)
@Deprecated("Use bindUniformInt1 instead", replaceWith = ReplaceWith("bindUniformInt1"))
fun ShaderBase<*>.uniform1i(uniformName: String, defaultVal: Int = 0) = bindUniformInt1(uniformName, defaultVal)
@Deprecated("Use bindUniformInt2 instead", replaceWith = ReplaceWith("bindUniformInt2"))
fun ShaderBase<*>.uniform2i(uniformName: String, defaultVal: Vec2i = Vec2i.ZERO) = bindUniformInt2(uniformName, defaultVal)
@Deprecated("Use bindUniformInt3 instead", replaceWith = ReplaceWith("bindUniformInt3"))
fun ShaderBase<*>.uniform3i(uniformName: String, defaultVal: Vec3i = Vec3i.ZERO) = bindUniformInt3(uniformName, defaultVal)
@Deprecated("Use bindUniformInt4 instead", replaceWith = ReplaceWith("bindUniformInt4"))
fun ShaderBase<*>.uniform4i(uniformName: String, defaultVal: Vec4i = Vec4i.ZERO) = bindUniformInt4(uniformName, defaultVal)
@Deprecated("Use bindUniformMat2f instead", replaceWith = ReplaceWith("bindUniformMat2f"))
fun ShaderBase<*>.uniformMat2f(uniformName: String, defaultVal: Mat2f = Mat2f.IDENTITY) = bindUniformMat2(uniformName, defaultVal)
@Deprecated("Use bindUniformMat3f instead", replaceWith = ReplaceWith("bindUniformMat3f"))
fun ShaderBase<*>.uniformMat3f(uniformName: String, defaultVal: Mat3f = Mat3f.IDENTITY) = bindUniformMat3(uniformName, defaultVal)
@Deprecated("Use bindUniformMat4f instead", replaceWith = ReplaceWith("bindUniformMat4f"))
fun ShaderBase<*>.uniformMat4f(uniformName: String, defaultVal: Mat4f = Mat4f.IDENTITY) = bindUniformMat4(uniformName, defaultVal)
@Deprecated("Use bindUniformFloat1Array instead", replaceWith = ReplaceWith("bindUniformFloat1Array"))
fun ShaderBase<*>.uniform1fv(uniformName: String, arraySize: Int = 0) = bindUniformFloat1Array(uniformName, arraySize)
@Deprecated("Use bindUniformFloat2Array instead", replaceWith = ReplaceWith("bindUniformFloat2Array"))
fun ShaderBase<*>.uniform2fv(uniformName: String, arraySize: Int = 0) = bindUniformFloat2Array(uniformName, arraySize)
@Deprecated("Use bindUniformFloat3Array instead", replaceWith = ReplaceWith("bindUniformFloat3Array"))
fun ShaderBase<*>.uniform3fv(uniformName: String, arraySize: Int = 0) = bindUniformFloat3Array(uniformName, arraySize)
@Deprecated("Use bindUniformFloat4Array instead", replaceWith = ReplaceWith("bindUniformFloat4Array"))
fun ShaderBase<*>.uniform4fv(uniformName: String, arraySize: Int = 0) = bindUniformFloat4Array(uniformName, arraySize)
@Deprecated("Use bindUniformInt1Array instead", replaceWith = ReplaceWith("bindUniformInt1Array"))
fun ShaderBase<*>.uniform1iv(uniformName: String, arraySize: Int = 0) = bindUniformInt1Array(uniformName, arraySize)
@Deprecated("Use bindUniformInt2Array instead", replaceWith = ReplaceWith("bindUniformInt2Array"))
fun ShaderBase<*>.uniform2iv(uniformName: String, arraySize: Int = 0) = bindUniformInt2Array(uniformName, arraySize)
@Deprecated("Use bindUniformInt3Array instead", replaceWith = ReplaceWith("bindUniformInt3Array"))
fun ShaderBase<*>.uniform3iv(uniformName: String, arraySize: Int = 0) = bindUniformInt3Array(uniformName, arraySize)
@Deprecated("Use bindUniformInt4Array instead", replaceWith = ReplaceWith("bindUniformInt4Array"))
fun ShaderBase<*>.uniform4iv(uniformName: String, arraySize: Int = 0) = bindUniformInt4Array(uniformName, arraySize)
@Deprecated("Use bindUniformMat2fArray instead", replaceWith = ReplaceWith("bindUniformMat2fArray"))
fun ShaderBase<*>.uniformMat2fv(uniformName: String, arraySize: Int = 0) = bindUniformMat2Array(uniformName, arraySize)
@Deprecated("Use bindUniformMat3fArray instead", replaceWith = ReplaceWith("bindUniformMat3fArray"))
fun ShaderBase<*>.uniformMat3fv(uniformName: String, arraySize: Int = 0) = bindUniformMat3Array(uniformName, arraySize)
@Deprecated("Use bindUniformMat4fArray instead", replaceWith = ReplaceWith("bindUniformMat4fArray"))
fun ShaderBase<*>.uniformMat4fv(uniformName: String, arraySize: Int = 0) = bindUniformMat4Array(uniformName, arraySize)

@Deprecated("Use bindUniformStruct instead", replaceWith = ReplaceWith("bindUniformStruct"))
fun <S: Struct> ShaderBase<*>.uniformStruct(uniformName: String, struct: S) = bindUniformStruct(uniformName, struct)

@Deprecated("Use bindTexture1d instead", replaceWith = ReplaceWith("bindTexture1d"))
fun ShaderBase<*>.texture1d(textureName: String, defaultVal: Texture1d? = null, defaultSampler: SamplerSettings? = null) = bindTexture1d(textureName, defaultVal, defaultSampler)
@Deprecated("Use bindTexture2d instead", replaceWith = ReplaceWith("bindTexture2d"))
fun ShaderBase<*>.texture2d(textureName: String, defaultVal: Texture2d? = null, defaultSampler: SamplerSettings? = null) = bindTexture2d(textureName, defaultVal, defaultSampler)
@Deprecated("Use bindTexture3d instead", replaceWith = ReplaceWith("bindTexture3d"))
fun ShaderBase<*>.texture3d(textureName: String, defaultVal: Texture3d? = null, defaultSampler: SamplerSettings? = null) = bindTexture3d(textureName, defaultVal, defaultSampler)
@Deprecated("Use bindTextureCube instead", replaceWith = ReplaceWith("bindTextureCube"))
fun ShaderBase<*>.textureCube(textureName: String, defaultVal: TextureCube? = null, defaultSampler: SamplerSettings? = null) = bindTextureCube(textureName, defaultVal, defaultSampler)

fun ShaderBase<*>.texture2dArray(textureName: String, defaultVal: Texture2dArray? = null, defaultSampler: SamplerSettings? = null) = bindTexture2dArray(textureName, defaultVal, defaultSampler)
fun ShaderBase<*>.textureCubeArray(textureName: String, defaultVal: TextureCubeArray? = null, defaultSampler: SamplerSettings? = null) = bindTextureCubeArray(textureName, defaultVal, defaultSampler)
fun ShaderBase<*>.storage(storageName: String, defaultVal: GpuBuffer? = null) = bindStorage(storageName, defaultVal)
fun ShaderBase<*>.storageTexture1d(storageTextureName: String, defaultVal: StorageTexture1d? = null, defaultMipLevel: Int = 0) = bindStorageTexture1d(storageTextureName, defaultVal, defaultMipLevel)
fun ShaderBase<*>.storageTexture2d(storageTextureName: String, defaultVal: StorageTexture2d? = null, defaultMipLevel: Int = 0) = bindStorageTexture2d(storageTextureName, defaultVal, defaultMipLevel)
fun ShaderBase<*>.storageTexture3d(storageTextureName: String, defaultVal: StorageTexture3d? = null, defaultMipLevel: Int = 0) = bindStorageTexture3d(storageTextureName, defaultVal, defaultMipLevel)
fun ShaderBase<*>.colorUniform(cfg: ColorBlockConfig) = bindColorUniform(cfg)
fun ShaderBase<*>.colorTexture(cfg: ColorBlockConfig) = bindColorTexture(cfg)
fun ShaderBase<*>.normalTexture(cfg: NormalMapConfig) = bindNormalTexture(cfg)
fun ShaderBase<*>.propertyUniform(cfg: PropertyBlockConfig) = bindPropertyUniform(cfg)
fun ShaderBase<*>.propertyTexture(cfg: PropertyBlockConfig) = bindPropertyTexture(cfg)
